#!/bin/bash
noir='\033[30m' gris='\033[1;30m' rouge='\033[31m' rose='\033[1;31m' vertfonce='\033[0;32m' vertclair='\033[1;32m' jaune='\033[1;33m' bleufonce='\033[0;34m' bleuclair='\033[1;34m' violetfonce='\033[0;35m' violetclair='\033[1;35m' cyanfonce='\033[0;36m' cyanclair='\033[1;36m' grisclair='\033[0;37m' blanc='\033[1;37m' neutre='\033[0m'
echo -e "${violetclair}What do you want to do${neutre}${vertclair}?${neutre} ${violetfonce}(add/status/log)${neutre}"
read action
if [ $action = status ]
then
	git status
	exit
elif [ $action = log ]
then
	git log
	exit
elif [ $action = add ]
then
	git add *
	echo -e "${cyanfonce}What is the name of the commit${neutre}${jaune}?${neutre}"
	read commit
	git commit -m $commit > ~/goinfre/commit 
	sleep 2
	git push 2>&1 > ~/goinfre/push
	echo -e "${vertfonce}Your work has been pushed${neutre}${rouge}.${neutre}"
	echo -e "${rose}If you want to see the commit result, enter${neutre} ${vertclair}commit${neutre}. ${rose}For push result, enter${neutre} ${vertclair}push${neutre}${rose}. Else, ${neutre}${vertclair}exit${neutre}${rose}.${neutre}"
fi
read $com
if [ $com = commit ]
then
	cat ~/goinfre/commit
elif [ $com = push ]
then
	cat ~/goinfre/push
elif [ $com = exit ]
then
	exit
fi
